### ISSUE TITLE
Code to convert NetCDF to OM

### ISSUE THREAD

**Issue by jovanovski** [open-meteo/open-data#19]
I'm trying to add custom NetCDF datasets to my self-hosted Open Meteo API. I want to convert them into the OM format for fast access, but am struggling to find the correct way to do it. Where can I find the existing function for this conversion?

**Comment by patrick-zippenfenig** [comment]
Hi,
sorry for the late reply. Busy week. Which dataset would you like to integrate? The easiest model with NetCDF is MetNo: https://github.com/open-meteo/open-meteo/blob/main/Sources/App/MetNo/MetNoDownloader.swift

We are also planing to offer a Python library that will be able to generate OM files and make the API code more generic. However, this will probably take half a year.

**Comment by filip-earthcare** [comment]
Hello @patrick-zippenfenig, I'm @jovanovski 's colleague. We have some custom NetCDF datasets generated from our own sensors that we would like to integrate into our self-hosted Open Meteo API. We are currently in the process of converting these datasets into the OM format to ensure fast access.

**Comment by jovanovski** [comment]
To add to Filip, we're trying to find the most optimal way of:

1. Converting a NetCDF file into the OM format (we took a look at the code for Met.no, but got stuck)
2. Adding that converted dataset as a separate model in our self-hosted OM API so it can be queried like existing models.

Can you point us in the right direction, as to what we need to modify to get this working (ex. what files need to be changed to have the API recognize a new model)?

**Comment by patrick-zippenfenig** [comment]
You mentioned sensors: Do you want to ingest unstructured measurements? Open-Meteo is only designed to work with gridded data like weather models, satellite or radar data.

To add a new model the workflow is not ideal, but you have to 
1. Copy the MetNo directory
2. Replace any "MetNo" with "YourModel"
3. Adjust any "weather variable" to the available variables from your model
4. Implement any derived variables in the controller. E.g. how to calculated wind speed from U/V components.
5. Adjust the download code to the specific model. Most models use GRIB, but NetCDF also works. The downloaders are a bit cumbersome because they need to process large amount of data in smaller chunks. Otherwise it would require too much memory.
6. Register the new model in the "ForecastController". The compiler will complain about some cases that need to be filled out. Namely the "Reader" needs to be defined. The definitions for Flatbuffers are not important and you can return any other domain name.

Everything is very verbose and explicitly defined. This has the advantage of making the system very robust against programming errors. The drawback is that there is a lot of code duplication. It would be feasible to implement an endpoint that just serves data from OM files with some meta-data in JSON. It is slowly evolving towards this point, but it will take some time as there is no business interest yet.

Happy to have a call with you to quickly discuss how you data can be integrated. Just send me a mail.

**Comment by filip-earthcare** [comment]
Hello @patrick-zippenfenig, we can schedule a call, you can contact me at filip.alempijevik@earthcare.ai. Looking forward to hearing from you!
