### ISSUE TITLE
CAPE for ERA5 or ECMWF not available in AWS

### ISSUE THREAD

**Issue by mcgregorian1** [open-meteo/open-data#6]
Hi Patrick, thank you so much for your work on this!

I am interested in getting historical data for convective available potential energy (CAPE), but I noticed that it's not available in the S3 bucket for the ERA5 or the ECMWF data. It is available as an option from the CDS but of course the API is not working. Do you know if eventually this will be part of Open-Meteo, or is there another way to access this data?

**Comment by patrick-zippenfenig** [comment]
Hi, it is correct, that I did not download CAPE for ERA5 or ECMWF IFS. Because of the massive size of ERA5, I was limiting myself to only the most popular weather variables. I understand that thermal stability is important and I integrate it for all weather forecast models (if available). You could extend the API code to download CAPE from ERA5 as well and start downloading, but it will probability take a couple of weeks to fetch data from CDS for the past 80 years.

**Comment by mcgregorian1** [comment]
Hi Patrick. Ok, that's what I thought, thanks for your response.

In case anyone else is looking for the data, I did find an archive version of CAPE from ERA5 (and all the other ERA5 variables) at the [National Center for Atmospheric Research (NCAR)](https://rda.ucar.edu/datasets/ds633.0/) website. I'm not sure if this is only available in the US, but I can confirm I can download data from here without issue.
